/*
 * GPIO_Config.c
 *
 *  Created on: 2017年5月25日
 *      Author: Arthur
 */

#include "GPIO_Config.h"

void GPIO_Init(void)
{
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
    GPIOPinTypeGPIOOutput(GPIO_PORTD_BASE, GPIO_PIN_0 | GPIO_PIN_1);
    GPIOPinWrite(GPIO_PORTD_BASE, GPIO_PIN_1, GPIO_PIN_1);
}

void ConfigureGPIOD(void)
{
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOD);
	GPIOPinTypeGPIOInput(GPIO_PORTD_BASE, GPIO_PIN_2);
	GPIOPadConfigSet(GPIO_PORTD_BASE, GPIO_PIN_2,GPIO_STRENGTH_2MA,GPIO_PIN_TYPE_STD_WPU);
	IntEnable(INT_GPIOD);
	GPIOIntTypeSet(GPIO_PORTD_BASE,GPIO_INT_PIN_2,GPIO_HIGH_LEVEL);
	GPIOIntEnable(GPIO_PORTD_BASE,GPIO_INT_PIN_2);
}

//void ConfigureGPIOF(void)
//{
//	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
//	HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = GPIO_LOCK_KEY;//解锁
//	HWREG(GPIO_PORTF_BASE + GPIO_O_CR) |= 0x01;//确认
//	HWREG(GPIO_PORTF_BASE + GPIO_O_LOCK) = 0;//重新锁定
//	GPIOPinTypeGPIOInput(GPIO_PORTF_BASE, GPIO_PIN_0);
//	GPIOPadConfigSet(GPIO_PORTF_BASE, GPIO_PIN_0,GPIO_STRENGTH_12MA,GPIO_PIN_TYPE_STD_WPU);
//	GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_0, GPIO_PIN_0);
//	IntEnable(INT_GPIOF);
//	GPIOIntTypeSet(GPIO_PORTF_BASE,GPIO_INT_PIN_0,GPIO_LOW_LEVEL);
//	GPIOIntEnable(GPIO_PORTF_BASE,GPIO_INT_PIN_0);
//}
